### ISSUE TITLE
Fix usage of multiple stages with same name

### ISSUE THREAD

**Issue by KalmanMeth** [netobserv/flowlogs-pipeline#333]
We saw an example with the following configuration:
```
pipeline:
- name: ingest_collector
- follows: ingest_collector
  name: transform_generic
- follows: transform_generic
  name: transform_network
- follows: transform_network
  name: extract_aggregate
- follows: transform_network
  name: extract_conntrack
- follows: extract_conntrack
  name: extract_aggregate
- follows: extract_aggregate
  name: encode_prom
```
The same stage (extract_aggregate) is specified twice as following 2 different stages. This was done to achieve the desired output, one with connection tracking and without.
Apparently this works because we now use channels as input, so a stage may receive from 2 different sources.
Not sure this is desired to be legal. We should probably have detected this and issued an error.
Ensure that things work as desgined, and provide the correct sequence of stages to achieve the desired outcome.
