### ISSUE TITLE
Kube enrichment not working in IPFIX export

### ISSUE THREAD

**Issue by rupertgregoryibm** [netobserv/flowlogs-pipeline#405]
Hey folks - suffering an issue whereby the kube enrichment doesn't appear to be working when exporting as IPFIX via FLP. At a bit of a loss where to start debugging as not overly familiar with this project, so any help appreciated.

Current workflow is 3x kube nodes running netobserv-ebpf-agent feeding in to flp via the grpc interface. FLP then 'enriches' and sends out IPFIX to our collector. At the moment the collector is showing enrichment for the sourcePodNamespace, but all other fields are showing 'none' (sourcePodName, destinationPodNamespace, destinationPodName, sourceNodeName).

I note in the flp code sourcePodNamespace is handled differently to the other values - is this an issue? or just the way it was coded?

https://github.com/netobserv/flowlogs-pipeline/blob/0269dcc8c4e2a9a555d3c9b12fb0c45d45f5e33e/pkg/pipeline/write/write_ipfix.go#L400

Configs for reference - 
agent:
`apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netobserv-ebpf-agent
  labels:
    k8s-app: netobserv-ebpf-agent
spec:
  selector:
    matchLabels:
      k8s-app: netobserv-ebpf-agent
  template:
    metadata:
      labels:
        k8s-app: netobserv-ebpf-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: netobserv-ebpf-agent
        image: quay.io/praveingk/netobserv-ebpf-agent:main
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: CACHE_ACTIVE_TIMEOUT
            value: 200ms
          - name: LOG_LEVEL
            value: debug
          - name: FLOWS_TARGET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: FLOWS_TARGET_PORT
            value: "9999"
`
flp:
`apiVersion: v1
kind: ConfigMap
metadata:
  name: flp-config
data:
  config.yaml: |
    log-level: debug
    pipeline:
      - name: ingest
      - name: enrich
        follows: ingest
      - name: write_ipfix
        follows: enrich
    parameters:
      - name: ingest
        ingest:
          type: grpc
          grpc:
            port: 9999
      - name: enrich
        transform:
          type: network
          network:
            rules:
              - input: SrcAddr
                output: SrcK8S
                type: "add_kubernetes"
              - input: DstAddr
                output: DstK8S
                type: "add_kubernetes"
      - name: write_ipfix
        write:
          type: ipfix
          ipfix:
            targetHost: x.x.x.x
            targetPort: 9996
            transport: udp
            enterpriseID: 27207
`

**Comment by eranra** [comment]
@praveingk I assume you will look into that. Just wanted to advice that @KalmanMeth might also be interested :-)

**Comment by praveingk** [comment]
@KalmanMeth : In the IPFIX export, the sourcePod, destPod, etc are named `"none"`, if record["sourcePodName"] == nil`
Any reasons why the kube enrichment process doesn't note them. Please advise if we are missing something from the config.

**Comment by KalmanMeth** [comment]
@praveingk  @rupertgregoryibm 
The IPFIX `write` stage expects fields to be named: `sourcePodNamespace, sourcePodName, sourceNodeName, destinationPodNamespace, destinationPodName, destinationNodeName`. **The incoming data does not have these fields.** The names for these fields in the current config are: `SrcK8S_Namespace, SrcK8S_Name, SrcK8S_HostName, DstK8S_Namespace, DstK8S_Name, DstK8S_HostName`. The prefixes `SrcK8S `and `DstK8S `come from the specification to the `enrich `stage.

To change the names of the fields, you can add another stage `transform generic` to rename fields:
```
      - name: rename
        transform:
          type: generic
          generic:
            rules:
              - input: SrcK8S_Name
                output: sourcePodName
              - input: DstK8S_Name
                output: destinationPodName
              - input: SrcK8S_HostName
                output: sourceNodeName
              - input: DstK8S_HostName
                output: destinationNodeName
              - input: SrcK8S_Namespace
                output: sourcePodNamespace
              - input: DstK8S_Namespace
                output: destinationPodNamespace
```
and the resulting pipeline is:
```
    pipeline:
      - name: ingest
      - name: enrich
        follows: ingest
      - name: rename
        follows: enrich
      - name: write_ipfix_km
        follows: rename
```
