### ISSUE TITLE
FLP doesn't handle empty list of labels in certain cases

### ISSUE THREAD

**Issue by emnahum** [netobserv/flowlogs-pipeline#464]
FLP has the problem that it produces metrics such as the following:

# HELP pano_dns_rcode_total
# TYPE pano_dns_rcode_total counter
pano_dns_rcode_total{rcode_name=""} 29944.01916207507
pano_dns_rcode_total{rcode_name="NOERROR"} 8147
pano_dns_rcode_total{rcode_name="NXDOMAIN"} 2865
pano_dns_rcode_total{rcode_name="SERVFAIL"} 26

The first entry with "" should not show up.

Here's a simple yaml config file where it does NOT happen:

[temp.txt](https://github.com/netobserv/flowlogs-pipeline/files/12162497/temp.txt)

Here's a more complex yaml file where it DOES happen:
[pano-file-dns.txt](https://github.com/netobserv/flowlogs-pipeline/files/12162512/pano-file-dns.txt)

(gave the files .txt extensions because github didn't understand yaml files, oddly enough)

Here's a log file to drive it with:

[dns-pano.log](https://github.com/netobserv/flowlogs-pipeline/files/12162527/dns-pano.log)

(note the yaml files include the config file in a yaml subdirectory)

**Comment by jotak** [comment]
Hi @emnahum ,
I guess this was the reason for https://github.com/netobserv/flowlogs-pipeline/pull/460 , but as I commented in this PR, I don't think this is a good solution to evict records that have empty labels.
What about doing this exact same thing, but by configuration? Ie adding a filter rule to drop records when `rcode_name` is absent? cf https://github.com/netobserv/flowlogs-pipeline/blob/main/docs/api.md#transform-filter-api / `remove_entry_if_doesnt_exist`

**Comment by jotak** [comment]
I haven't try, but maybe something like that could work?
(adding two new stages, `filter_dns` and `encode_prom_dns`)

```yaml
log-level: error
metricsSettings:
  port: 9102
  suppressGoMetrics: true
  prefix: pano_dns_
pipeline:
  - name: ingest_file
  - name: aggregate_values
    follows: ingest_file
  - name: encode_prom
    follows: aggregate_values
  - name: filter_dns
    follows: aggregate_values
  - name: encode_prom_dns
    follows: filter_dns
parameters:
  - name: ingest_file
    ingest:
      type: file_loop
      file:
        filename: logs/dns-pano.log
        decoder:
          type: json
  - name: aggregate_values
    extract: 
      type: aggregates
      aggregates: 
        rules:
        - name: aggr_rtt_avg
          operationType: avg
          operationKey: rtt
        - name: aggr_rtt_hist
          operationType: raw_values
          operationKey: rtt
        - name: qtype_count
          groupByKeys:
            - qtype_name
          operationType: count
          operationKey: qtype
        - name: query_count
          groupByKeys:
            - query
          operationType: count
          operationKey: query
        - name: rcode_count
          groupByKeys:
            - rcode_name
          operationType: count
          operationKey: rcode
  - name: encode_prom
    encode:
      type: prom
      prom:
        prefix: pano_dns_
        metrics:
        - name: query_count
          type: counter
        - name: query_total
          type: counter
          valueKey: recent_op_value
          labels:
           - query
        - name: qtype_total
          type: counter
          valueKey: recent_op_value
          labels:
            - qtype_name
        - name: rtt_histogram
          type: agg_histogram
          valueKey: recent_raw_values
          buckets:
           - 0.00001
           - 0.0001
           - 0.001
           - 0.01
           - 0.10
           - 1.00
        - name: rtt_avg
          type: gauge
          valueKey: recent_op_value
          filter: {key: name, value: aggr_rtt_avg}
  - name: filter_dns
    transform:
    - type: filter
      filter:
        rules:
        - input: rcode_name
          type: remove_entry_if_doesnt_exist
  - name: encode_prom_dns
    encode:
      type: prom
      prom:
        prefix: pano_dns_
        metrics:
        - name: rcode_total
          type: counter
          valueKey: recent_op_value
          labels:
            - rcode_name
```
