### ISSUE TITLE
support JSON input with nested objects fields

### ISSUE THREAD

**Issue by aslom** [netobserv/flowlogs-pipeline#480]
I have input JSON with topic fields inside child customData:

```JSON
{"id":"fb1a463c-8a27-4cc2-9f0c-bd991c3802d6",
"eventTime":"2023-08-27T13:38:13.373726754Z",
"customData":{"valid":"0","offset":"0","topic":"topic1"}
}
```

How would I do `addIf` for `customData.topic`?

```YAML
          - type: add_if
            input: customData.topic
            parameters: '== "topic1"'
            output: classification
            assignee: high
```

@ronensc 
@eranra
