### ISSUE TITLE
conditions with mulriplr fields?

### ISSUE THREAD

**Issue by aslom** [netobserv/flowlogs-pipeline#481]
For input JSON:

I have input JSON with topic fields inside child customData:

```JSON
{"id":"fb1a463c-8a27-4cc2-9f0c-bd991c3802d6",
"initiatorIp": "127.0.0.1",
"topic":"topic1"
}
```

How would I do `addIf` condition based on two fields?

```YAML
    rules:
          - type: add_if
            input: topic initiatorIp
            parameters: 'topic == "topic1" && initiatorIp="127.0.0.1"'
            output: compliance_boundary
            assignee: high
```

@ronensc 
@eranra
