### ISSUE TITLE
Debuggin and tracing write Loki setup and connection

### ISSUE THREAD

**Issue by aslom** [netobserv/flowlogs-pipeline#482]
Is there a flag or some other way to see DEBUG/ or TRACE log with connection to Loki and what is sent there?

Right now I have simple pipeline with 

```
  - name: write_loki
    write:
      type: loki
      loki:
        url: http://localhost:3100
        staticLabels:
          job: flowlogs-pipeline
```

and it runs without errors (and no output) even if there is nothing on localhost:3100 ( checked with `curl -v localhost:3100/ready` fails)

@ronensc 
@eranra
