### ISSUE TITLE
metricsSettings - suppressGoMetrics results in not metrics at all

### ISSUE THREAD

**Issue by Nachtfalkeaw** [netobserv/flowlogs-pipeline#944]
Hello,

I use this config:
```
metricsSettings:
  suppressGoMetrics: true
  prefix: flp_operational_
  port: 9102
```

If I set `suppressGoMetrics: true` I do not get any metrics at all. If I set it to "false" I receive Go Metrics and the other expected metrics.
