### ISSUE TITLE
decode_tcp_flags in Rules not working as expected (Translate to string)

### ISSUE THREAD

**Issue by Nachtfalkeaw** [netobserv/flowlogs-pipeline#946]
Hello,

documentation says:
```
                 decode_tcp_flags: Decode bitwise TCP flags into a string
                     input: entry input field
                     output: entry output field
```

My pipline looks like this and I would like to get the "17" as a STRING.
The other types have additional parameters like "subnet_mask: /24" but for decode_tcp_flags there is none.
I would like to see a mapping like:
17 = FIN-ACK
18 = SYN-ACK
1 = FIN
4 = RST

```
parameters:
  - name: ipfix_netflow_ingest
    ingest:
      type: collector
      collector:
        hostName: u999fmlab001l
        port: 2055

  - name: transform_add_subnet
    transform:
      type: network
      network:
        rules:
          - type: add_subnet
            add_subnet:
              input: SrcAddr
              output: SrcSubnet24
              subnet_mask: /24
          - type: add_subnet
            add_subnet:
              input: SrcAddr
              output: SrcSubnet16
              subnet_mask: /16
          - type: add_subnet
            add_subnet:
              input: DstAddr
              output: DstSubnet24
              subnet_mask: /24
          - type: add_subnet
            add_subnet:
              input: DstAddr
              output: DstSubnet16
              subnet_mask: /16
          - type: decode_tcp_flags
            decode_tcp_flags:
              input: TcpFlags
              output: TcpFlagsString

```

I am not sure if this is the intention of the transformation or if I do something wrong in my config pipline.
