### ISSUE TITLE
Aggregate timeouts do not behave as expected

### ISSUE THREAD

**Issue by johnhtodd** [netobserv/flowlogs-pipeline#981]
I have a configuration line like this with the pipeline path SubnetRTTAvg->TrimAvgFields->PromAvg

```
  - name: SubnetRTTAvg
    extract:
      type: aggregates
      aggregates:
        rules:
          - name: "Average for subnet"
            groupByKeys:
                - SrcSubnet
            operationType: avg
            operationKey: TimeFlowRttNs
            expiryTime: 3600

  - name: TrimAvgFields
    transform:
        type: filter
        filter:
          rules:
          - type: remove_field
            removeField:
              input: recent_count
          - type: remove_field
            removeField:
              input: recent_op_value
          - type: remove_field
            removeField:
              input: recent_raw_values
          - type: remove_field
            removeField:
              input: name
          - type: remove_field
            removeField:
              input: aggregate
          - type: remove_field
            removeField:
              input: by

  - name: PromAvg
    encode:
      type: prom
      prom:
        prefix: flowlog_
        metrics:
          - name: AvgRTTNS
            type: gauge
            valueKey: total_value
            labels:
              - SrcSubnet
```

However, I see the counters being reset every ~2 minutes.  I have also tried setting "defaultExpiryTime: 3600" and similar results.  With these settings, I would expect the counters to reset at 3600 seconds, not at 120 seconds.

My stdout for a selected item - note the timestamps and total_count roll:

```
Jun  3 04:52:45.435: map[SrcSubnet:192.168.23.210/32 operation_key:TimeFlowRttNs operation_type:avg total_count:31 total_value:4.702967741935484e+06]
Jun  3 04:52:50.419: map[SrcSubnet:192.168.23.210/32 operation_key:TimeFlowRttNs operation_type:avg total_count:2 total_value:5.257e+06]
. . .
Jun  3 04:54:45.435: map[SrcSubnet:192.168.23.210/32 operation_key:TimeFlowRttNs operation_type:avg total_count:21 total_value:6.171571428571428e+06]
Jun  3 04:54:50.419: map[SrcSubnet:192.168.23.210/32 operation_key:TimeFlowRttNs operation_type:avg total_count:3 total_value:6.540333333333333e+06]
. . .
```

**Comment by jotak** [comment]
Hi @johnhtodd 
I suspect the 2min expiry is due to another mechanism that happens not in the aggregate stage, but in the metrics/prom stage. Here also, there's a mechanism to make metrics expiring, see https://github.com/netobserv/flowlogs-pipeline/blob/main/docs/api.md#prometheus-encode-api `expiryTime`. This is a way to avoid memory leaks. If you want, you can set a higher value such as `expiryTime: "5h"`


Also ; unrelated to your question, but looking at your config I am wondering maybe it's more optimal to skip the aggregation stage and use a metric of type Histogram instead. It's an alternative to do basically the same thing (and not limited to keeping the avg), and perhaps offers better performances. Also, `gauge` metrics are inaccurate, they wouldn't capture any spike that happen between 2 prometheus scrape events.

Basically you would just have this config:

```yaml
  - name: PromHistogram
    encode:
      type: prom
      prom:
        prefix: flowlog_
        metrics:
          - name: HistRTTNS
            type: histogram
            valueKey: TimeFlowRttNs
            labels:
              - SrcSubnet
```

which would result in metrics like that:

```
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="0.005"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="0.01"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="0.025"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="0.05"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="0.1"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="0.25"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="0.5"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="1"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="2.5"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="5"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="10"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="10.0.0.0/24",le="+Inf"} 1
flowlog_HistRTTNS_sum{SrcSubnet="10.0.0.0/24"} 0.2
flowlog_HistRTTNS_count{SrcSubnet="10.0.0.0/24"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="0.005"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="0.01"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="0.025"} 0
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="0.05"} 1
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="0.1"} 2
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="0.25"} 2
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="0.5"} 2
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="1"} 2
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="2.5"} 2
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="5"} 2
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="10"} 2
flowlog_HistRTTNS_bucket{SrcSubnet="20.0.0.0/24",le="+Inf"} 2
flowlog_HistRTTNS_sum{SrcSubnet="20.0.0.0/24"} 0.15000000000000002
flowlog_HistRTTNS_count{SrcSubnet="20.0.0.0/24"} 2
```

With those metrics in promQL, you can query the average (`flowlog_HistRTTNS_sum/flowlog_HistRTTNS_count`) or percentiles (using `histogram_quantile`)
